# This is a basic workflow to help you get started with Actions

name: Docker Build & Push

on:
  push:
    tags:        
      - '*'           # Push events to every tag not containing /
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
  DOCKER_USERNAME: buddymurdock
  DOCKER_CONTAINER_NAME: caddy-cloudflare
  DOCKER_TARGET_PLATFORM: linux/amd64

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 
            buddymurdock/caddy-cloudflare:latest
